name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY_HOST: docker.pkg.github.com
  IMAGE_TAG: $REGISTRY_HOST/$GITHUB_REPOSITORY/image:base 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_TAG

    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY_HOST -u ${{ github.actor }} --password-stdin
    
    - name: Push image
      run: docker push ${{ github.repository }} $IMAGE_TAG
